# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Desktop\Portfolio\C++\Coursework\Cryptography_with_Qt\code\aboutprogramm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutProgramm(object):
    def setupUi(self, AboutProgramm):
        AboutProgramm.setObjectName("AboutProgramm")
        AboutProgramm.resize(421, 387)
        AboutProgramm.setMinimumSize(QtCore.QSize(421, 387))
        AboutProgramm.setMaximumSize(QtCore.QSize(421, 387))
        AboutProgramm.setSizeIncrement(QtCore.QSize(421, 387))
        AboutProgramm.setBaseSize(QtCore.QSize(421, 387))
        AboutProgramm.setStyleSheet("QWidget {\n"
" background-color: rgb(45, 45, 48);\n"
"}")
        self.label = QtWidgets.QLabel(AboutProgramm)
        self.label.setGeometry(QtCore.QRect(10, 10, 401, 371))
        self.label.setMinimumSize(QtCore.QSize(401, 371))
        self.label.setMaximumSize(QtCore.QSize(401, 371))
        self.label.setSizeIncrement(QtCore.QSize(401, 371))
        self.label.setBaseSize(QtCore.QSize(401, 371))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet("border-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color: rgb(220, 220, 220);\n"
"\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(AboutProgramm)
        QtCore.QMetaObject.connectSlotsByName(AboutProgramm)

    def retranslateUi(self, AboutProgramm):
        _translate = QtCore.QCoreApplication.translate
        AboutProgramm.setWindowTitle(_translate("AboutProgramm", "Form"))
        self.label.setText(_translate("AboutProgramm", "Program encoder / decode\n"
"Written by: student: Zakharchuk Yuri Alexandrovich\n"
"Course: 2\n"
"Group: KB-213\n"
"The program is capable of encrypting both text and binary files,\n"
"decrypting previously encrypted files.\n"
"Create new files as needed and open them.The program\n"
"has several types of ciphers with their brief description."))
