# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Desktop\Portfolio\C++\Coursework\Cryptography_with_Qt\code\helpwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelpWindow(object):
    def setupUi(self, HelpWindow):
        HelpWindow.setObjectName("HelpWindow")
        HelpWindow.setEnabled(True)
        HelpWindow.resize(515, 511)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(51)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HelpWindow.sizePolicy().hasHeightForWidth())
        HelpWindow.setSizePolicy(sizePolicy)
        HelpWindow.setMinimumSize(QtCore.QSize(515, 511))
        HelpWindow.setMaximumSize(QtCore.QSize(515, 511))
        HelpWindow.setSizeIncrement(QtCore.QSize(515, 511))
        HelpWindow.setBaseSize(QtCore.QSize(515, 511))
        HelpWindow.setStyleSheet("QWidget {\n"
" background-color: rgb(45, 45, 48);\n"
"}")
        self.label = QtWidgets.QLabel(HelpWindow)
        self.label.setGeometry(QtCore.QRect(10, 10, 491, 151))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color: rgb(220, 220, 220);\n"
"\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(HelpWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 491, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color: rgb(220, 220, 220);\n"
"\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(HelpWindow)
        self.label_3.setGeometry(QtCore.QRect(10, 340, 491, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color: rgb(220, 220, 220);\n"
"\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(HelpWindow)
        QtCore.QMetaObject.connectSlotsByName(HelpWindow)

    def retranslateUi(self, HelpWindow):
        _translate = QtCore.QCoreApplication.translate
        HelpWindow.setWindowTitle(_translate("HelpWindow", "Form"))
        self.label.setText(_translate("HelpWindow", "Create file - select/create a file, and immediately fill it with text through\n"
"the opened window.\n"
"Open file - opens a file for further work with it.\n"
"File data - Displays file information on the screen.\n"
"Delete - removes a file from the program\'s memory, thus making it\n"
"impossible to work with it further."))
        self.label_2.setText(_translate("HelpWindow", "Encoding tab:\n"
"Operating instructions:\n"
"1) Create/Open a data file.\n"
"2) Select the desired cipher.\n"
"3) Press the encoding button, after which the screen will show that the job\n"
"is done.\n"
"Note: 3.1) After clicking, a file with a key for further decryption will be created.\n"
"3.2) A file will be created, the format previously selected for encryption,\n"
"the file will contain encrypted text."))
        self.label_3.setText(_translate("HelpWindow", "Decipher tab:\n"
"Operating instructions:\n"
"1) Select the appropriate decryptor for the encrypted file.\n"
"2) Select the key created earlier by the program for the file.\n"
"3) Select the encrypted file.\n"
"4) Press the Decipher button, after which the screen\n"
"will show that the job is done.\n"
" Note: 4.1) A file will be created in which the decrypted file will be written."))
