# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Desktop\Portfolio\C++\Coursework\Cryptography_with_Qt\code\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 519)
        MainWindow.setMinimumSize(QtCore.QSize(809, 519))
        MainWindow.setMaximumSize(QtCore.QSize(809, 519))
        MainWindow.setStyleSheet("QWidget {\n"
" background-color: rgb(45, 45, 48);\n"
"}\n"
"\n"
"QMenuBar {\n"
" background-color: rgb(45, 45, 48);\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    spacing: 3px;           \n"
"    padding: 2px 10px;\n"
"    background-color: rgb(210,105,30);\n"
"    color: rgb(255,255,255);  \n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {    \n"
"background-color: rgb(210,105,30);\n"
"}\n"
"QMenuBar::item:pressed {\n"
"background-color: rgb(210,105,30);\n"
"}\n"
"\n"
"/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */  \n"
"\n"
"QMenu {\n"
"  background-color: rgb(45, 45, 48);\n"
"    border: 1px solid black;\n"
"    margin: 1px;\n"
"}\n"
"QMenu::item {\n"
"background-color: rgb(210,105,30);\n"
"}\n"
"QMenu::item:selected { \n"
"background-color: rgb(210,105,30);\n"
"    color: rgb(255,255,255);\n"
"}\n"
"")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 541, 131))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 2px solid rgb(61, 61, 68);\n"
"border-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color: rgb(220, 220, 220);\n"
"\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(610, 10, 141, 131))
        self.widget.setStyleSheet("\n"
"background-color: rgb(220, 220, 220);\n"
"\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setMouseTracking(True)
        self.pushButton.setStyleSheet("QPushButton:hover{\n"
"border: 1px solid  rgb(181, 181, 181);\n"
"    background-color: rgb(181, 181, 181);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 40, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton:hover{\n"
"border: 1px solid  rgb(181, 181, 181);\n"
"    background-color: rgb(181, 181, 181);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 100, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton:hover{\n"
"border: 1px solid  rgb(181, 181, 181);\n"
"    background-color: rgb(181, 181, 181);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 70, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton:hover{\n"
"border: 1px solid  rgb(181, 181, 181);\n"
"    background-color: rgb(181, 181, 181);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 150, 711, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid  rgb(181, 181, 181);\n"
"    background-color: rgb(181, 181, 181);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(9, 9, 691, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(9, 144, 681, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 240, 681, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid  rgb(181, 181, 181);\n"
"    background-color: rgb(181, 181, 181);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(252, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(590, 60, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid  rgb(181, 181, 181);\n"
"    background-color: rgb(181, 181, 181);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(252, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(590, 100, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid  rgb(181, 181, 181);\n"
"    background-color: rgb(181, 181, 181);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 809, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menuVersia = QtWidgets.QMenu(self.menuBar)
        self.menuVersia.setObjectName("menuVersia")
        self.menuLanguage = QtWidgets.QMenu(self.menuBar)
        self.menuLanguage.setObjectName("menuLanguage")
        self.menuReference = QtWidgets.QMenu(self.menuBar)
        self.menuReference.setObjectName("menuReference")
        MainWindow.setMenuBar(self.menuBar)
        self.actionRussian = QtWidgets.QAction(MainWindow)
        self.actionRussian.setObjectName("actionRussian")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionCreate_file = QtWidgets.QAction(MainWindow)
        self.actionCreate_file.setObjectName("actionCreate_file")
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout_the_program = QtWidgets.QAction(MainWindow)
        self.actionAbout_the_program.setObjectName("actionAbout_the_program")
        self.actionHelp_2 = QtWidgets.QAction(MainWindow)
        self.actionHelp_2.setObjectName("actionHelp_2")
        self.menu.addAction(self.actionCreate_file)
        self.menu.addAction(self.actionOpen_file)
        self.menu.addAction(self.actionClose)
        self.menuLanguage.addAction(self.actionRussian)
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuReference.addAction(self.actionHelp_2)
        self.menuReference.addAction(self.actionAbout_the_program)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menuLanguage.menuAction())
        self.menuBar.addAction(self.menuReference.menuAction())
        self.menuBar.addAction(self.menuVersia.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Selected file / Data from file"))
        self.pushButton.setText(_translate("MainWindow", "Create file"))
        self.pushButton_2.setText(_translate("MainWindow", "Open file"))
        self.pushButton_3.setText(_translate("MainWindow", "Delete"))
        self.pushButton_4.setText(_translate("MainWindow", "File data"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Choose the desired cipher"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Vernam cipher"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Caesar\'s cipher"))
        self.label_2.setText(_translate("MainWindow", "Here is a description of the selected cipher"))
        self.pushButton_5.setText(_translate("MainWindow", "Encoding"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Encoding"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Choose the right decoder"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Vernam cipher"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Caesar\'s cipher"))
        self.label_3.setText(_translate("MainWindow", "Encrypted message output"))
        self.pushButton_6.setText(_translate("MainWindow", "Decipher"))
        self.label_4.setText(_translate("MainWindow", "Select file with key"))
        self.pushButton_7.setText(_translate("MainWindow", "Select Key"))
        self.label_5.setText(_translate("MainWindow", "Select an encrypted file"))
        self.pushButton_8.setText(_translate("MainWindow", "Select Enc"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Decipher"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.menuVersia.setTitle(_translate("MainWindow", "Version 0.1.22"))
        self.menuLanguage.setTitle(_translate("MainWindow", "Language"))
        self.menuReference.setTitle(_translate("MainWindow", "Reference"))
        self.actionRussian.setText(_translate("MainWindow", "Russian"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
        self.actionCreate_file.setText(_translate("MainWindow", "Create "))
        self.actionOpen_file.setText(_translate("MainWindow", "Open"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionAbout_the_program.setText(_translate("MainWindow", "About the program"))
        self.actionHelp_2.setText(_translate("MainWindow", "Help"))
